# Generated by Django 5.1.5 on 2025-01-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('song', models.FileField(upload_to='songs/')),
                ('author', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Track',
            },
        ),
    ]
