# Generated by Django 5.1.5 on 2025-01-17 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_track_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='user',
        ),
        migrations.AddField(
            model_name='track',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
